# Generated by Django 4.2 on 2023-04-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(blank=True, choices=[('usd', 'usd'), ('gbp', 'gbp'), ('euro', 'euro')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
