# Generated by Django 4.2 on 2023-05-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_userprofile_currency_alter_userprofile_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('GBP', 'GBP'), ('EURO', 'EURO')], max_length=100, null=True),
        ),
    ]
