# Generated by Django 4.2 on 2023-04-30 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_userprofile_currency_alter_userprofile_balance'),
        ('payapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
