# Generated by Django 4.2 on 2023-04-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_rename_message_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
